# Generated by Django 5.2.12 on 2026-03-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
