# Generated by Django 5.2.12 on 2026-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_request_timestamp_request_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
